//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerIsCepteAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateDocuments
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string DocumentPath { get; set; }
    }
}
