//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerIsCepteAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definitions
    {
        public int ID { get; set; }
        public Nullable<int> Value { get; set; }
        public string Description { get; set; }
        public string Parameter { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
