//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerIsCepteAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictsAndCities
    {
        public int ID { get; set; }
        public string SehirIlceMahalleAdi { get; set; }
        public Nullable<int> UstID { get; set; }
        public string minlongitude { get; set; }
        public string minlatitude { get; set; }
        public string maxlongitude { get; set; }
        public string maxlatitude { get; set; }
        public string MahalleID { get; set; }
    }
}
