//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerIsCepteAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HerIsCepteEntities : DbContext
    {
        public HerIsCepteEntities()
            : base("name=HerIsCepteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<AdvertisementDocuments> AdvertisementDocuments { get; set; }
        public virtual DbSet<AdvertisementQuestion> AdvertisementQuestion { get; set; }
        public virtual DbSet<Advertisements> Advertisements { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<BlogPhoto> BlogPhoto { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<CorporateApplications> CorporateApplications { get; set; }
        public virtual DbSet<CorporateDocuments> CorporateDocuments { get; set; }
        public virtual DbSet<Definitions> Definitions { get; set; }
        public virtual DbSet<DistrictsAndCities> DistrictsAndCities { get; set; }
        public virtual DbSet<FavoriteAdvertisements> FavoriteAdvertisements { get; set; }
        public virtual DbSet<FavoriteCategories> FavoriteCategories { get; set; }
        public virtual DbSet<FavoriteLocations> FavoriteLocations { get; set; }
        public virtual DbSet<Help> Help { get; set; }
        public virtual DbSet<MessageRooms> MessageRooms { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<NotificationSettings> NotificationSettings { get; set; }
        public virtual DbSet<Offers> Offers { get; set; }
        public virtual DbSet<Packages> Packages { get; set; }
        public virtual DbSet<PackageTransactions> PackageTransactions { get; set; }
        public virtual DbSet<PaymentTemp> PaymentTemp { get; set; }
        public virtual DbSet<QuestionAnswers> QuestionAnswers { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<SEO> SEO { get; set; }
        public virtual DbSet<SubCategories> SubCategories { get; set; }
        public virtual DbSet<TopCategories> TopCategories { get; set; }
        public virtual DbSet<UserPackage> UserPackage { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
        public virtual DbSet<UserTableTemp> UserTableTemp { get; set; }
    }
}
